### ISSUE TITLE
Adding the new [member](); after the 3rd drop with Alt

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#25] opened 2016-03-28 07:03 UTC
This is the result of dropping the same member for 3 times using Alt:
![2016-03-28_09h59_25](https://cloud.githubusercontent.com/assets/18003268/14072746/ec0685c6-f4cb-11e5-84f4-d169524de9f8.jpg)

As you can see the 3rd one is with New, the others are like dropping without the Alt

**Comment by stickleprojects** [comment] 2016-03-28 09:58
HI
After (2), the code is treating Categories as a method, and so [Alt]+[Dropping a class]+[into a method] is executing. Root cause is dropping incomplete code into the editor.
The only workaround is to ensure your code compiles before dragging and dropping. Any thoughts welcomed

**Comment by stickleprojects** [comment] 2017-03-23 23:33
Closing as no constructive comments

**Closed as completed by stickleprojects** 2017-03-23 23:33 UTC
