### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#24] opened 2016-03-28 06:58 UTC
After dropping 2 times, the 3rd one will be indented with no real reason:
![2016-03-28_09h56_37](https://cloud.githubusercontent.com/assets/18003268/14072713/a052174e-f4cb-11e5-837e-b53079402e0f.jpg)

**Comment by stickleprojects** [comment] 2016-03-28 09:59
Hi, after (2), Categories is deemed to be a function and so indentation is kicking in. This is because you would need to close the previous statement with a ";"

**Comment by stickleprojects** [comment] 2017-03-23 23:35
Closing as expected behaviour

**Closed as completed by stickleprojects** 2017-03-23 23:35 UTC
