### ISSUE TITLE
VS2017 - When dragging a file/class with alt it drops the class name instead of new class

### ISSUE THREAD

**Issue by vlellouche** [stickleprojects/VSDropAssist#31] opened 2017-02-21 13:41 UTC
In previous version when droping a file/class using the <kbd>alt</kbd> key the result was 
```cs
new Namespace.ClassName();
```

In the 2017 version the result is:
```cs
Namespace.ClassName
```

**Comment by stickleprojects** [comment] 2017-02-22 18:12
Resolved in latest commit (debug binaries atached below). Issue was caused by multiple drop-handlers matching the data you were dropping. Resolved by adjusting the search so that the keyboard has more importance in the matching algo.

[VSDropAssist.zip](https://github.com/FireflyMigration/VSDropAssist/files/794401/VSDropAssist.zip)

**Closed as completed** 2017-02-22 18:16 UTC
