### ISSUE TITLE
3rd drop has the wrong result

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#27] opened 2016-03-28 07:11 UTC
This is the result of the following sequence:
1. Alt
2. Alt
3. Shift

![2016-03-28_10h08_34](https://cloud.githubusercontent.com/assets/18003268/14072896/3a38e170-f4cd-11e5-9e55-8248605a5e0f.jpg)

The 3rd one should be "public readonly [member]..."

**Comment by stickleprojects** [comment] 2016-03-28 09:56
Hi, this is caused by the code not compiling after (2), and is treating Categories as a method..
Note that there is no specific action for Alt+[dropping a class]+[onto a class outside of a method], so you are seeing the same as holding no keys for (1) and (2)

**Comment by stickleprojects** [comment] 2017-03-23 23:36
Closing as expected behaviour - the VS editor will format code that doesnt compile

**Closed as completed by stickleprojects** 2017-03-23 23:36 UTC
